name: Publish

on:
  release:
    types: [published]

jobs:
  publish:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest]
        rust: [stable]

    steps:
    - uses: hecrj/setup-rust-action@v2
      with:
        rust-version: ${{ matrix.rust }}
    - uses: actions/checkout@main
    - name: Login to crates.io
      run: cargo login $CRATES_IO_TOKEN
      env:
        CRATES_IO_TOKEN: ${{ secrets.crates_io_token }}
    - name: Dry run publish opaque-ke
      run: cargo publish --dry-run --manifest-path Cargo.toml
    - name: Publish opaque-ke
      run: cargo publish --manifest-path Cargo.toml
      env:
        CARGO_REGISTRY_TOKEN: ${{ secrets.crates_io_token }}